categories:
- product
conversations:
- - hi
  - 請問需要甚麼幫助?

- - Hey
  - 需要什麼幫忙嗎? 

- - hello
  - 需要我幫忙什麼?

- - 你好
  - 你好, 很高興為您服務

- - 嗨
  - 嗨, 需要我幫忙什麼?




- - 我想找一瓶 (雪碧)
  - 以下是 (雪碧) 的詳細資料,價格為 (30) 元, (590) 毫升, 內含熱量為 (230) 卡

- - 我要找 (雪碧) (cola) 位置 在哪
  - 好, 馬上幫你查一下, (雪碧) 的地點在 (A區), 如下圖

- - 我想找一瓶 (茶裏王)
  - 好, 幫你查一下 (茶裏王), 以下是 你要的詳細資料,價格為 (25) 元, (590) 毫升, 內含熱量為 (230) 卡

- - 我要找 (茶裏王) 位置 在哪
  - 好, 馬上幫你查一下, (茶裏王) 的地點在 (A區), 如下圖




- - 我需要一包 (衛生紙)
  - 衛生紙的價格為 (30) 元

- - 我要找 (衛生紙) 位置 在哪
  - 好, 馬上幫你查一下, (衛生紙) 的地點在 (B區), 如下圖

- - 請問 (刮鬍刀) 我需要
  - 好, 馬上幫你查一下,以下是 (刮鬍刀) 的詳細資料,價格為 (20) 元

- - 我要找 (刮鬍刀) 位置 在哪
  - 好, 馬上幫你查一下, (刮鬍刀) 的地點在 (B區), 如下圖




- - 我要找一碗 (阿Q桶麵)
  - 以下是 (阿Q桶麵) 的詳細資料,價格為 (35) 元, 內含熱量為 (500) 卡

- - 我要找 (阿Q桶麵) 位置 在哪
  - 好, 馬上幫你查一下, (阿Q桶麵) 的地點在 (C區), 如下圖

- - 我要找一包 (維力炸醬麵)
  - 以下是 (維力炸醬麵) 的詳細資料,價格為 (25) 元, 內含熱量為 (300) 卡

- - 我要找 (維力炸醬麵) 位置 在哪
  - 好, 馬上幫你查一下, (維力炸醬麵) 的地點在 (C區), 如下圖




- - 我想找一罐 (可樂) (cola)
  - 沒問題, 以下是 (可樂) 的詳細資料,價格為 (30) 元, (380) 毫升, 內含熱量為 (222) 卡

- - 我要找 (可樂) (cola) 位置 在哪
  - 沒問題, (可樂) 的地點在 (A區), 如下圖

- - 我需要找一罐 (伯朗咖啡) (Mr.brown coffee)
  - 好, 馬上幫你查一下,以下是 (伯朗咖啡) (Mr.brown coffee) 的詳細資料,價格為 (30) 元, (200) 毫升, 內含熱量為 (200) 卡

- - 我要找 (伯朗咖啡) 位置 在哪
  - 好, 馬上幫你查一下, (伯朗咖啡) 的地點在 (A區), 如下圖




- - 我需要一包 (樂事原味洋芋片) (Lay's Original)
  - 好的, 以下是 (樂事原味洋芋片) 的詳細資料,價格為 (30) 元, 內含熱量為 (400) 卡

- - 我要找 (樂事原味洋芋片) (Lay's Original) 位置 在哪
  - 好的, (樂事原味洋芋片) 的地點在 (D區), 如下圖

- - 我需要一個 (義美泡芙) 
  - 好, 馬上幫你查一下,以下是 (義美泡芙) 的詳細資料,價格為 (40) 元, 內含熱量為 (250) 卡

- - 我要找 (義美泡芙) 位置 在哪
  - 好, 馬上幫你查一下, (義美泡芙) 的地點在 (D區), 如下圖
